[package]
description = "TonboRecord macro"
documentation = "https://docs.rs/tonbo_macros"
edition = "2021"
license = "Apache-2.0"
name = "tonbo_macros"
version = "0.3.2"

[dependencies]
darling = "0.20"
proc-macro2 = "1"
quote = "1"
syn = "2"

[lib]
path = "src/lib.rs"
proc-macro = true
