[package]
edition = "2024"
name = "predicate"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[features]
default = []

[dependencies]
roaring = "0.11"
typed-arrow-dyn = { git = "https://github.com/tonbo-io/typed-arrow.git", package = "typed-arrow-dyn", features = [
    "serde",
] }
