[package]
edition = "2024"
name = "predicate"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[features]
default = []

[dependencies]
async-trait = "0.1"
datafusion-expr = "50"
roaring = "0.11"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
